[package]
name = "rusty-tape"
version = "0.1.0"
authors = ["Petros Angelatos <petrosagg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
tokio = { version = "0.2", features = [ "macros" ] }
scraper = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
percent-encoding = "2"
rayon = "1.5"

[profile.release]
lto = true
opt-level = 's'
panic = 'abort'
